id = "monokai-night"
name = "Monokai Night Theme"
schema_version = 1
version = "0.2.2"
authors = ["farbodvand <pharbod95@gmail.com>"]
description = "🌃 A dark theme with two accents and vibrant syntax highlighting for Zed."
repository = "https://github.com/farbodvand/zed-monokai-night"
